spring:
  application:
    name: "cards"
  config:
    import: "optional:configserver:http://localhost:9090/"
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: root
    password: root
    database-platform: org.hibernate.dialect.H2Dialect
    console:
      enabled:true
  profiles:
    active: "prod"

server:
  port: 8081
